description = ""
images = []
metaDescriptionOrder = ["description", "site"]
robots = ["max-image-preview:large"]
keywords = []

[header]
  logo = ""
  maxLogoSize = 80.0
  disableTextInHeader = false
  centerLogo = false

[footer]
  showMenu = true

[breadcrumb]
  showBreadcrumb = true
  showCurrentPage = true

[sidebar]
  enabled = true

  [[sidebar.widgets]]
    type = "featured"
    title = "おすすめの投稿"
    limit = 5

  [[sidebar.widgets]]
    type = "recent"
    title = "最近の投稿"
    section = "posts"
    limit = 5

  [[sidebar.widgets]]
    type = "categories"
    title = "カテゴリー"

[social]
  twitter = ""
  facebook_app_id = ""
